openapi: 3.0.3
info:
  title: PWA Builder API
  description: Azure functions based API for PWABuilder, Tools and Extensions.
    [Repository](https://github.com/pwa-builder/pwabuilder-api-v2).
  version: 2.1.0
servers:
  - url: /api
paths:
  /FetchWebManifest:
    get:
      summary: Manifest file
      description: Detect and grab manifest json and url from webapp
      tags:
        - Generate
      parameters:
        - $ref: components.yaml#/parameters/site
      responses:
        "200":
          $ref: components.yaml#/responses/manifestGrab/200
  /GenerateManifest:
    get:
      deprecated: true
      summary: Generate manifest file
      description: Detect and parse or generate manifest json from webapp
      tags:
        - Generate
      parameters:
        - $ref: components.yaml#/parameters/site
      responses:
        "200":
          $ref: components.yaml#/responses/manifestGen/200
  /Hint:
    get:
      summary: Hint report
      description: Generate PWA-related Hint report for webapp
      tags:
        - Report
      parameters:
        - $ref: components.yaml#/parameters/site
      responses:
        "200":
          description: OK
  /Offline:
    get:
      deprecated: true
      summary: Check offline
      description: Validate webapp for offline support
      tags:
        - Validate
      parameters:
        - $ref: components.yaml#/parameters/site
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      offline:
                        type: string
  /Report:
    get:
      summary: Lighthouse report
      description: Generate PWA-related Lighthouse report for webapp
      tags:
        - Report
      parameters:
        - $ref: components.yaml#/parameters/site
        - name: desktop
          schema:
            type: boolean
          in: query
          description: Use desktop form factor
          required: false
      responses:
        "200":
          $ref: components.yaml#/responses/report/200
  /Security:
    get:
      summary: Check webapp security
      description: Validate webapp security protocols
      tags:
        - Validate
      parameters:
        - $ref: components.yaml#/parameters/site
      responses:
        "200":
          $ref: components.yaml#/responses/security/200
  /Site:
    get:
      deprecated: true
      summary: Custom report
      description: Custom manifest validation
      tags:
        - Report
      parameters:
        - $ref: components.yaml#/parameters/site
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  content:
                    type: object
                    $ref: manifest.yaml
                  format:
                    type: string
                  generatedUrl:
                    type: string
                  id:
                    type: number
                  default:
                    type: object
                  errors:
                    type: array
                    items:
                      type: object
                  suggestions:
                    type: array
                    items:
                      type: object
                  warnings:
                    type: array
                    items:
                      type: object
  /WebManifest:
    post:
      deprecated: true
      summary: Check webmanifest
      description: Validate webapp manifest
      tags:
        - Validate
      parameters:
        - name: site
          schema:
            type: string
            default: https://webboard.app
          in: query
          description: Web application URL
      requestBody:
        description: Optional body params
        content:
          application/json:
            schema:
              type: object
              properties:
                manifest:
                  type: object
                  default: null
                maniurl:
                  type: string
                  default: null
      responses:
        "200":
          $ref: components.yaml#/responses/manifestGrab/200
components: {}
tags: []
