openapi: 3.0.3
info:
  title: PWA Builder API
  description: Azure functions based API for PWABuilder, Tools and Extensions. [Repository](https://github.com/pwa-builder/pwabuilder-api-v2).
  version: '2.0'
servers:
  - url: /api

components:
  schemas: 
    manifest:
      $ref: 'manifest.yaml'
  parameters:
    site:
      name: site
      schema: 
        type: string
        default: https://webboard.app
      in: query
      description: Web application URL
      required: true
  responses:
    manifestGrab:
      '200':
        description: OK
        content: 
          application/json:
            schema: 
              type: object
              properties: 
                content:
                  type: object
                  properties: 
                    json:
                      $ref: '#/components/schemas/manifest'
                    url:
                      type: string
    # manifestGen:
    #   '200':
    #     description: OK
    #     content: 
    #       application/json:
    #         schema: 
    #           type: object
    #           properties: 
    #             content:
    #               type: object
    #               $ref: 'manifest.yaml'
    #             format:
    #               type: string
    #             generatedUrl: 
    #               type: string
    security:
      '200':
        description: OK
        content: 
          application/json:
            schema: 
              type: object
              properties: 
                data:
                  type: object
                  properties:
                    isHTTPS:
                      type: boolean
                    validProtocol:
                      type: boolean
                    valid:
                      type: boolean
    report:
      '200':
        description: OK
        content: 
          application/json:
            schema: 
              type: object
              properties: 
                data:
                  type: object
                  properties:
                    audits:
                      type: object
                      properties:
                        isOnHttps:
                          type: object
                          properties:
                            score:
                              type: boolean
                        installableManifest:
                          type: object
                          properties:
                            score:
                              type: boolean
                            details: 
                              type: object
                              properties:
                                url:
                                  type: string
                        serviceWorker:
                          type: object
                          properties:
                            score:
                              type: boolean
                            details: 
                              type: object
                              properties:
                                url:
                                  type: string
                                scope:
                                  type: string
                        appleTouchIcon:
                          type: object
                          properties:
                            score:
                              type: boolean
                        maskableIcon:
                          type: object
                          properties:
                            score:
                              type: boolean
                        splashScreen:
                          type: object
                          properties:
                            score:
                              type: boolean
                        themedOmnibox:
                          type: object
                          properties:
                            score:
                              type: boolean
                        viewport:
                          type: object
                          properties:
                            score:
                              type: boolean
                    artifacts:
                      type: object
                      properties:
                        webAppManifest:
                          type: object
                          properties:
                            raw:
                              type: string
                            url:
                              type: string
                            value:
                              type: object
                        url: 
                          type: object
                          properties:
                            finalUrl:
                              type: string
                            requestedUrl:
                              type: string
                        serviceWorker:
                          type: object
                          properties:
                            registrations:
                              type: array
                              items:
                                type: object
                            versions:
                              type: array
                              items:
                                type: object
                        linkElements:
                              type: array
                              items:
                                type: object
                        metaElements:
                              type: array
                              items:
                                type: object



paths:                       
  /FetchWebManifest:
    post:
      summary: Grab manifest file
      description: 'Detect and grab manifest json and url from webapp'
      tags:
        - Manifest
      parameters:
        - $ref: '#/components/parameters/site'
      responses:
        '200':
          $ref: '#/components/responses/manifestGrab/200'
    get:
      summary: Grab manifest file
      description: 'Detect and grab manifest json and url from webapp'
      tags:
        - Manifest
      parameters:
        - $ref: '#/components/parameters/site'
      responses:
        '200':
          $ref: '#/components/responses/manifestGrab/200'
  
  /Security:
    post:
      summary: Check webapp security
      description: Validate webapp security protocols
      tags:
        - Validate
      parameters:
        - $ref: '#/components/parameters/site'
      responses:
        '200':
          $ref: '#/components/responses/security/200'

  /Report:
    post:
      summary: Check webapp validation
      description: Validate webapp
      tags:
        - Validate
      parameters:
        - $ref: '#/components/parameters/site'
      responses:
        '200':
          $ref: '#/components/responses/report/200'