# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - pwabuilder-tests

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://pwabuilder.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_c06c7d3e5eee412a977477fd52054f4a }}
        password: ${{ secrets.AzureAppService_ContainerPassword_2a264c144d9c48519b00a1ec34153f0a }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: pwabuilder.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_c06c7d3e5eee412a977477fd52054f4a }}/pwabuildertests:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'pwabuilder-tests'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_dfe3b9a55fac4f85babb0d868ac2c06b }}
        images: 'pwabuilder.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_c06c7d3e5eee412a977477fd52054f4a }}/pwabuildertests:${{ github.sha }}'