# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - pwabuilder-tests-preview

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://pwabuilder.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_a425dfc6de1f4bcd9a227d9ef01d162f }}
        password: ${{ secrets.AzureAppService_ContainerPassword_1e95af6a2b2e49a7a40e65905599cb97 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: pwabuilder.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_a425dfc6de1f4bcd9a227d9ef01d162f }}/pwabuildertests-dev:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'pwabuilder-tests-preview'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_151f76faeb21415d8e8e8999d514b251 }}
        images: 'pwabuilder.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_a425dfc6de1f4bcd9a227d9ef01d162f }}/pwabuildertests-dev:${{ github.sha }}'