name: Docker Image CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag pwabuilder.azurecr.io/pwabuildertests:staging

      - name: Login
        run: docker login pwabuilder.azurecr.io -u pwabuilder --password ${{secrets.azure}}

      - name: Push
        run: docker push pwabuilder.azurecr.io/pwabuildertests:staging

  build-pr:
    runs-on: ubuntu-latest
    if: github.event.name == 'pull_request'

    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker Image for a PR
        run: docker build . --file Dockerfile
