name: pwabuilder-apiv2-node to prod (Publish Profile)

on:
  workflow_dispatch:  # Manual trigger for testing
  # push:
  #   branches: ["master"]

env:
  AZURE_FUNCTIONAPP_NAME: 'pwabuilder-apiv2-node' 
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.' 
  NODE_VERSION: '18.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4
      timeout-minutes: 5
          
    - name: Setup Node ${{ env.NODE_VERSION }} Environment
      uses: actions/setup-node@v4
      timeout-minutes: 5
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: 'Install dependencies'
      timeout-minutes: 15
      run: |
        echo "Installing dependencies..."
        npm ci --prefer-offline --no-audit
        echo "Dependencies installed successfully"

    - name: 'Build project'
      timeout-minutes: 10
      run: |
        echo "Building project..."
        npm run build
        echo "Build completed successfully"

    - name: 'Prepare for deployment'
      timeout-minutes: 5
      run: |
        echo "Pruning dev dependencies..."
        npm prune --production
        echo "Deployment preparation completed"
        ls -la dist/

    - name: 'Deploy to Azure Functions'
      uses: Azure/functions-action@v1
      timeout-minutes: 15
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
