name: Deploy to Preview

on:
  push:
    branches: [ dev ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag pwabuilder.azurecr.io/pwabuildertests-dev:latest
      
    - name: Login
      run: docker login pwabuilder.azurecr.io -u pwabuilder --password ${{secrets.azure}}
      
    - name: Push
      run: docker push pwabuilder.azurecr.io/pwabuildertests-dev:latest
